import { A } from "@solidjs/router";
import { CONTACT_EMAIL } from "../links.ts";

export function Terms() {
  const mail = () => <a class="qa-contact-email" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>;
  return (
    <article class="qa-terms">
      <h1 class="h4 mb-1">Terms of service</h1>
      <p class="text-body-secondary small">Last updated 30 September 2026</p>

      <p>Ditto is a free language-practice app run by Topher Hunt ("we"). By using it you agree to these terms. How we handle your data is covered by the <A href="/privacy">privacy policy</A>.</p>

      <h2 class="h5 mt-4">Your account</h2>
      <ul class="d-flex flex-column gap-2">
        <li>You must be 16 or older to use Ditto.</li>
        <li>You sign in with a Google account. One account per person, and you're responsible for what happens on yours.</li>
        <li>Your username is public to other learners. Pick one that doesn't impersonate anyone and isn't offensive.</li>
      </ul>

      <h2 class="h5 mt-4">Using Ditto fairly</h2>
      <p>Don't:</p>
      <ul class="d-flex flex-column gap-2">
        <li>harass, threaten or spam other learners, including with friend requests or board posts;</li>
        <li>post anything hateful, sexual, or someone else's personal information;</li>
        <li>create extra accounts to get around the daily AI allowance, a block or a suspension;</li>
        <li>scrape the app, overload it, or try to get into accounts or data that aren't yours.</li>
      </ul>
      <p>You can block and report other learners from their profile.</p>

      <h2 class="h5 mt-4">AI features</h2>
      <p>Explanations, conversation partners, feedback and some audio are generated by AI (OpenAI). They are usually helpful but can be wrong, so treat them as practice, not authority. Don't share sensitive personal information in conversations: what you say and type there is sent to OpenAI. The free daily AI allowance may change, and AI features may be paused if costs require it.</p>

      <h2 class="h5 mt-4">Content</h2>
      <p>What you write and say stays yours. You let us store what you write and process what you write and say, including sending it to OpenAI as the privacy policy describes, only to run Ditto for you and, for board posts and usernames, to show it to other learners. The course content and audio are for your personal learning.</p>

      <h2 class="h5 mt-4">Moderation and ending your account</h2>
      <p>We may remove board posts, reset usernames, and suspend or delete accounts that break these terms. You can stop using Ditto any time and ask us to delete your account by emailing {mail()}.</p>

      <h2 class="h5 mt-4">The service</h2>
      <p>Ditto is provided free and as is. We may change, pause or discontinue features or the whole service. If we shut it down, we'll give notice when we can, so you can ask for a copy of your data. To the extent the law allows, we aren't liable for any loss from using Ditto or from it being unavailable. Nothing here limits rights you have under consumer protection law that can't be waived.</p>

      <h2 class="h5 mt-4">Changes</h2>
      <p>We'll update the date above when these terms change and announce significant changes in the app. Continuing to use Ditto after a change means you accept it.</p>

      <h2 class="h5 mt-4">Contact</h2>
      <p>Questions: {mail()}.</p>
    </article>
  );
}
